name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - name: Update npm to latest version
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Publish to npm with provenance
        run: npm publish --provenance --access public
